name: Deploy Backend
on:
  push:
    branches:
      - deploy
      - main
      

jobs:
  deploy_qa:
    if: github.ref == 'refs/heads/deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Secrets
        run: |
          echo "HOST: ***${{ secrets.HOST:0:3 }}***"
          echo "USERNAME: ***${{ secrets.USERNAME:0:3 }}***"
          echo "PORT: ***${{ secrets.SSH_PORT }}***"
          echo "PRIVATE_KEY starts with: ***$(echo "${{ secrets.PRIVATE_KEY }}" | cut -c1-10)***"
