name: Deploy Backend
on:
  push:
    branches:
      - deploy
      - main
      

jobs:
  deploy:
    if: github.ref == 'refs/heads/deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Secrets
        run: |
          echo "HOST: ***$(echo "${{ secrets.HOST }}" | cut -c1-5)***"
          echo "USERNAME: ***$(echo "${{ secrets.USERNAME }}" | cut -c1-3)***"
          echo "PORT: ***${{ secrets.SSH_PORT }}***"
          echo "PRIVATE_KEY starts with: ***$(echo "${{ secrets.PRIVATE_KEY }}" | head -c 10)***"

