name: Deploy Backend
on:
  push:
    branches:
      - deploy
      - main

jobs:
  deploy:
    if: github.ref == 'refs/heads/deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect with VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Source the shell configuration files
            source ~/.bashrc
            source ~/.profile
            
            # Print environment information for debugging
            echo "Current PATH: $PATH"
            echo "Node version: $(node -v)"
            echo "NPM version: $(npm -v)"
            echo "PM2 version: $(pm2 -v)"
            
            # Navigate to the project directory
            mkdir -p apps/lms/backend && cd apps/lms/backend

            # Clone or pull the repository
            if [ -d ".git" ]; then
              git stash
              git pull origin deploy
            else
              git clone -b deploy https://github.com/pgvda/LMS-Supun-BackEnd.git .
            fi

            # Install dependencies and start the application
            npm install --force
            npm start

            # Check if the PM2 process exists and handle accordingly
            if pm2 list | grep -q "lms-backend"; then
              echo "Reloading application"
              pm2 reload "lms-backend"
            else
              echo "Starting new application"
              pm2 start npm --name "lms-backend" -- start
            fi

            # Save the PM2 process list
            pm2 save

